project_id = "eawddtedfvljgbfuxyfq"

[functions.submit-song]
verify_jwt = false

[functions.process-submissions]
verify_jwt = false

[functions.feeling-journey]
verify_jwt = false

[functions.migrate-legacy-songs]
verify_jwt = false
